#!/bin/sh

touch "$HOME"/.psqlrc.local

mkdir -p "$HOME"/.config/nvim

ln -s "$HOME"/.vimrc "$HOME"/.config/nvim/init.vim

if [ -e "$HOME"/.local/share/nvim/site/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
fi
nvim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

reset -Q
