#!/bin/sh

touch "$HOME"/.psqlrc.local

mkdir -p "$HOME"/.config/nvim

if [ ! -e $HOME/.config/nvim/init.vim ]; then
  ln -s "$HOME"/.vimrc "$HOME"/.config/nvim/init.vim
fi


if [ -e "$HOME"/.local/share/nvim/site/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
fi
nvim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa


if [ ! -e /opt/homebrew/bin/brew ]; then
  /opt/homebrew/bin/brew bundle $HOME/dotfiles/Brewfile
fi

if [ ! -e /usr/local/bin/brew ]; then
  arch -x86_64 /usr/local/bin/brew bundle $HOME/dotfiles/Brewfile
fi

reset -Q
